import type { NextPage } from 'next';
import Head from 'next/head';

import { CustomerForm } from '@partials/customer/CustomerForm';
import { wrapper } from '@store/redux';
import { permissionMiddleware } from '@utils/middleware/permission';
import { getOrgasRequest } from '@actions/hr/get-orgas';
import { END } from 'redux-saga';
import { getUsersRequest } from '@actions/hr/get-users';
import { getCompaniesRequest } from '@actions/hr/get-companies';

const CreateCustomer: NextPage = () => {
    return (
        <>
            <Head>
                <title>고객등록</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <CustomerForm mode="create" spe="customer" />
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    permissionMiddleware(async ({ dispatch, sagaTask }) => {
        dispatch(
            getOrgasRequest({
                idx: '1',
            }),
        );

        dispatch(getCompaniesRequest('long-view'));

        dispatch(getCompaniesRequest('car-view'));

        dispatch(getCompaniesRequest('gen-view'));

        dispatch(
            getUsersRequest({
                idx: '1',
            }),
        );

        dispatch(END);

        await sagaTask?.toPromise();

        return null;
    }),
);

export default CreateCustomer;
