import type { NextPage } from 'next';
import type { AppState } from '@reducers/index';
import type { HrState } from '@reducers/hr';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useSelector } from 'react-redux';
import { END } from 'redux-saga';
import dayjs from 'dayjs';
import { MyTable } from '@components/table';
import { wrapper } from '@store/redux';
import { MyPagination } from '@components/pagination';
import { MyLayout } from '@components/Layout';
import { useColumn } from '@hooks/use-column';
import { permissionMiddleware } from '@utils/middleware/permission';
import { UserSearchFilter } from '@partials/hr/user/template/SearchFilter';
import { searchUsersRequest } from '@actions/hr/search-users.action';
import { SearchResultTemplate } from '@partials/common/template/SearchResult';
import { getOrgasRequest } from '@actions/hr/get-orgas';

const Users: NextPage = () => {
    const displayName = 'wr-pages-list2';

    const router = useRouter();

    const { searchUsers } = useSelector<AppState, HrState>((props) => props.hr);

    const columns = useColumn(searchUsers.fields);

    const handleClickRow = ({ userid }: any) => {
        router.replace(`${router.pathname}/${userid}`);
    };

    return (
        <>
            <Head>
                <title>영업가족</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <div className={displayName}>
                    <UserSearchFilter />
                    <SearchResultTemplate
                        total={searchUsers.total.count}
                        pageName="조직관리 / 영업가족"
                    />
                    <div className={`${displayName}__body`}>
                        <div className="wr-table--scrollable wr-table--hover">
                            <MyTable
                                columns={columns}
                                data={searchUsers.rows}
                                pageSize={searchUsers.lastPayload?.nums}
                                onClickRow={handleClickRow}
                            />
                        </div>
                    </div>
                    <div className={`${displayName}__footer`}>
                        <MyPagination
                            total={searchUsers.total.count}
                        ></MyPagination>
                    </div>
                </div>
            </MyLayout>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    permissionMiddleware(async ({ dispatch, sagaTask }, ctx) => {
        const { page, nums, order, date, user, date_type, status, ...rest } =
            ctx.query;

        const params: any = {
            page: 1,
            nums: 25,
            condition: {
                indate: [
                    dayjs(new Date()).format('YYYY-MM-01'),
                    dayjs(new Date()).format('YYYY-MM-DD'),
                ],
                status: ['상근', '비상근', '기타'],
            },
            order: {},
        };
        // 페이지공통 - 페이지 번호
        if (page) {
            params.page = Number(page);
        }
        // 페이지공통 - 페이지 크기
        if (nums) {
            params.nums = Number(nums);
        }
        // 페이지공통 - 정렬
        if (order) {
            const [type, sort] = String(order).split(',');

            params.order[type] = sort;
        }
        // 영업가족
        if (user) {
            params.idx = String(user);
        }
        // 재직현황
        if (status) {
            params.status = String(status).split(',');
        }
        // 입사일 및 퇴사일
        if (date_type && date) {
            params.condition[String(date_type)] = String(date).split(',');
        }

        // 영업조직, 영업구분, 협회등록, 검색...
        for (const [key, value] of Object.entries(rest)) {
            params.condition[key] = value;
        }

        dispatch(
            getOrgasRequest({
                idx: '1',
            }),
        );

        dispatch(searchUsersRequest(params));

        dispatch(END);

        try {
            await sagaTask?.toPromise();
        } catch (e) {
            // console.log(e);
        }

        return null;
    }),
);

export default Users;
