import type { NextPage } from 'next';
import Head from 'next/head';
import { END } from 'redux-saga';
import { getOrgasRequest } from '@actions/hr/get-orgas';
import { wrapper } from '@store/redux';
import { permissionMiddleware } from '@utils/middleware/permission';
import { UserForm } from '@partials/hr/UserForm';
import { getBanksRequest } from '@actions/hr/get-banks';
import { getAgenciesRequest } from '@actions/hr/get-agencys';

const CreateUser: NextPage = () => {
    return (
        <>
            <Head>
                <title>영업가족등록</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <UserForm mode="create" />
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    permissionMiddleware(async ({ dispatch, sagaTask }) => {
        dispatch(
            getOrgasRequest({
                idx: '1',
            }),
        );

        dispatch(getBanksRequest());

        dispatch(getAgenciesRequest());

        dispatch(END);

        await sagaTask?.toPromise();

        return null;
    }),
);

export default CreateUser;
