import type { NextPage } from 'next';
import type { CoreSelectOption, CoreTabOption } from '@interfaces/core';
import Head from 'next/head';
import { useState } from 'react';
import { useDispatch } from 'react-redux';
import { END } from 'redux-saga';
import { wrapper } from '@store/redux';
import { MySelect } from '@components/select';
import { DETAIL_PAGE_TABS } from '@constants/tab';
import { MyTab } from '@components/tab';
import { IncomeSettings } from '@partials/detail/tabpanels/IncomeSettings';
import { GuaranteeSettings } from '@partials/detail/tabpanels/GuaranteeSettings';
import { AuthoritySettings } from '@partials/detail/tabpanels/AuthoritySettings';
import { QualSettings } from '@partials/detail/tabpanels/QualSettings';
import { WithLabel } from '@components/WithLabel';
import { MyInput } from '@components/input';
import variables from '@styles/_variables.module.scss';
// 임시
import {
    getBasicPaymentsRequest,
    getBasicPaymentsSuccess,
} from '@actions/long/get-basic-payments.action';
import {
    getOverridesRequest,
    getOverridesSuccess,
} from '@actions/long/get-overrides.action';
import { MyLayout } from '@components/Layout';
import { ASIDE_MENU_CONTRACT } from '@constants/gnb';
// import { AccessibleText } from '@components/AccessibleText';

const WITH_SELECT_SIZE = 100;

const SELECT_HEIGHT = variables.detailFilterHeight;

const LongDetail: NextPage = () => {
    const dispatch = useDispatch();

    const [tab, setTab] = useState<CoreTabOption>(DETAIL_PAGE_TABS[0]);

    const [d, setD] = useState<[Date, Date] | null>([
        new Date('2022-02-01'),
        new Date('2022-03-01'),
    ]);

    const [org, setOrg] = useState<CoreSelectOption | null>(null);

    const handleClickTab = (tab: CoreTabOption) => {
        setTab(tab);
    };

    const handleChange = (org: CoreSelectOption | null) => {
        setOrg(org);
    };

    const handleChangeDate = (value: [Date, Date] | null) => {
        setD(value);
    };

    return (
        <>
            <Head>
                <title>상세페이지</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout
                menu={ASIDE_MENU_CONTRACT}
                footer={
                    <div>
                        <span>취소</span>
                        <span>수정</span>
                    </div>
                }
            >
                <div className="wr-pages-detail wr-form row">
                    <div className="col-4">
                        <div className="wr-pages-detail__left">
                            <div className="wr-pages-detail__block">
                                <div className="wr-mt">
                                    <div className="wr-group">
                                        <span className="wr-pages-detail__department">
                                            직할 영업 &#62; 5회사임직원 &#62;
                                            전산개발실
                                        </span>
                                        <button
                                            className="btn btn-primary btn-sm"
                                            type="button"
                                        >
                                            부서변경
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div className="wr-pages-detail__block">
                                <div className="row">
                                    <div className="col-8">
                                        <WithLabel
                                            id="cNum"
                                            label="사원번호"
                                            type="disable"
                                        >
                                            <MyInput
                                                type="text"
                                                id="cNum"
                                                placeholder="W1057"
                                                readOnly
                                            />
                                        </WithLabel>
                                        <WithLabel
                                            id="cName"
                                            label="고객명"
                                            type="disable"
                                        >
                                            <MyInput
                                                type="text"
                                                id="cName"
                                                placeholder="홍길동"
                                                readOnly
                                            />
                                        </WithLabel>
                                        <WithLabel
                                            id="cTitle"
                                            label="직함"
                                            type="disable"
                                        >
                                            <MyInput
                                                type="text"
                                                id="cTitle"
                                                placeholder="실장"
                                                readOnly
                                            />
                                        </WithLabel>
                                        <WithLabel
                                            id="sNum"
                                            label="주민번호"
                                            type="disable"
                                        >
                                            <MyInput
                                                type="text"
                                                id="sNum"
                                                placeholder="121212-2*******"
                                                readOnly
                                                button={{
                                                    type: 'button',
                                                    children: (
                                                        <>
                                                            <span>보기</span>
                                                        </>
                                                    ),
                                                }}
                                            />
                                        </WithLabel>
                                        <WithLabel
                                            id="cBirth"
                                            label="생년월일"
                                            type="active"
                                        >
                                            <div className="wr-pages-detail__with">
                                                <MyInput
                                                    type="text"
                                                    id="cBirth"
                                                    placeholder="1912-12-12"
                                                    readOnly
                                                />
                                                <MySelect
                                                    inputId="cBirth"
                                                    options={[]}
                                                    value={org}
                                                    onChange={() => {}}
                                                    placeholder={'양력'}
                                                    placeHolderFontSize={16}
                                                    height={
                                                        variables.detailFilterHeight
                                                    }
                                                />
                                            </div>
                                        </WithLabel>
                                        <WithLabel
                                            id="cPhone"
                                            label="핸드폰"
                                            type="active"
                                        >
                                            <div className="wr-pages-detail__with">
                                                <MyInput
                                                    type="text"
                                                    id="cPhone"
                                                    placeholder="010-1234-5678"
                                                />
                                                <MySelect
                                                    options={[]}
                                                    value={org}
                                                    onChange={() => {}}
                                                    placeholder={'KT'}
                                                    placeHolderFontSize={16}
                                                    height={
                                                        variables.detailFilterHeight
                                                    }
                                                />
                                            </div>
                                        </WithLabel>
                                        <WithLabel
                                            id="cExtPhone"
                                            label="내선번호"
                                            type="active"
                                        >
                                            <div className="wr-pages-detail__with">
                                                <MyInput
                                                    type="text"
                                                    id="cExtPhone"
                                                    placeholder="070-4881-6052"
                                                />
                                                <MyInput
                                                    type="text"
                                                    placeholder="6052"
                                                />
                                            </div>
                                        </WithLabel>
                                    </div>
                                    <div className="col-4">
                                        <div className="wr-ml">
                                            <div className="wr-pages-detail__avatar">
                                                <img
                                                    src="http://via.placeholder.com/200x198"
                                                    className="img-thumbnail"
                                                    alt="..."
                                                />
                                            </div>
                                            <WithLabel
                                                id="sFamily"
                                                label="영업가족"
                                                type="active"
                                            >
                                                <MySelect
                                                    inputId="sFamily"
                                                    options={[]}
                                                    value={org}
                                                    onChange={() => {}}
                                                    placeholder={'FRC'}
                                                    placeHolderFontSize={16}
                                                    height={
                                                        variables.detailFilterHeight
                                                    }
                                                />
                                            </WithLabel>
                                            <WithLabel
                                                id="eStatus"
                                                label="재직현황"
                                                type="active"
                                            >
                                                <MySelect
                                                    inputId="eStatus"
                                                    options={[]}
                                                    value={org}
                                                    onChange={() => {}}
                                                    placeholder={'상근'}
                                                    placeHolderFontSize={16}
                                                    height={
                                                        variables.detailFilterHeight
                                                    }
                                                />
                                            </WithLabel>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="wr-pages-detail__block">
                                <div className="row">
                                    <div className="col">
                                        <WithLabel
                                            id="cEmail"
                                            label="이메일"
                                            type="active"
                                        >
                                            <div className="wr-pages-detail__with">
                                                <MyInput
                                                    type="email"
                                                    id="cEmail"
                                                    placeholder="yoongiekim@naver.com"
                                                />
                                                <MySelect
                                                    options={[]}
                                                    value={org}
                                                    onChange={() => {}}
                                                    placeholder={'naver'}
                                                    placeHolderFontSize={16}
                                                    height={
                                                        variables.detailFilterHeight
                                                    }
                                                />
                                            </div>
                                        </WithLabel>
                                        <div className="row wr-mt wr-mb">
                                            <div className="col-5">
                                                <WithLabel
                                                    id="cAddr"
                                                    label="주소"
                                                    type="active"
                                                >
                                                    <div className="wr-pages-detail__with">
                                                        <MyInput
                                                            type="text"
                                                            id="cAddr"
                                                            placeholder="08195"
                                                            readOnly
                                                            button={{
                                                                type: 'button',
                                                                children: (
                                                                    <>
                                                                        <span>
                                                                            찾기
                                                                        </span>
                                                                    </>
                                                                ),
                                                            }}
                                                        />
                                                    </div>
                                                </WithLabel>
                                            </div>
                                            <div className="col-7">
                                                <div className="wr-ml">
                                                    <MyInput
                                                        type="email"
                                                        placeholder="경기도 안양시 동안구 시민대로 383"
                                                        readOnly
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                        <WithLabel
                                            id="cDetailAddr"
                                            label="상세주소"
                                            type="active"
                                        >
                                            <MyInput
                                                type="text"
                                                id="cDetailAddr"
                                                placeholder="B동 1102호"
                                            />
                                        </WithLabel>
                                        <div className="row wr-mt wr-mb">
                                            <div className="col-6">
                                                <WithLabel
                                                    id="eDate"
                                                    label="입사일"
                                                    type="active"
                                                >
                                                    <MyInput
                                                        type="text"
                                                        id="eDate"
                                                        placeholder="2023-02-11"
                                                    />
                                                </WithLabel>
                                            </div>
                                            <div className="col-6">
                                                <div className="wr-ml">
                                                    <WithLabel
                                                        id="dDate"
                                                        label="퇴사일"
                                                        type="active"
                                                    >
                                                        <MyInput
                                                            type="text"
                                                            id="dDate"
                                                            placeholder="2023-02-11"
                                                        />
                                                    </WithLabel>
                                                </div>
                                            </div>
                                        </div>
                                        <WithLabel
                                            id="attractor"
                                            label="유치자"
                                            type="active"
                                        >
                                            <MyInput
                                                type="text"
                                                id="attractor"
                                                placeholder="홍길순 (W0010)"
                                                readOnly
                                                button={{
                                                    type: 'button',
                                                    children: (
                                                        <>
                                                            <span>찾기</span>
                                                        </>
                                                    ),
                                                }}
                                            />
                                        </WithLabel>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-8">
                        <div className="wr-pages-detail__right">
                            <ul className="wr-tab__wrap" role="tablist">
                                {DETAIL_PAGE_TABS.map((v) => (
                                    <MyTab
                                        key={v.id}
                                        onClick={handleClickTab}
                                        isActive={v.id === tab.id}
                                        {...v}
                                    />
                                ))}
                                <li className="wr-tab__line"></li>
                            </ul>
                            <div className="wr-pages-detail__body">
                                <IncomeSettings
                                    hidden={tab.id !== 'tabIncome'}
                                    {...tab}
                                />
                                <GuaranteeSettings
                                    hidden={tab.id !== 'tabGuarantee'}
                                    {...tab}
                                />
                                <AuthoritySettings
                                    hidden={tab.id !== 'tabAuthority'}
                                    {...tab}
                                />
                                <QualSettings
                                    hidden={tab.id !== 'tabQual'}
                                    {...tab}
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </MyLayout>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    ({ dispatch, sagaTask }) =>
        async (_) => {
            dispatch(
                getBasicPaymentsRequest({
                    successAction: getBasicPaymentsSuccess,
                    callback: () => {},
                }),
            );

            dispatch(
                getOverridesRequest({
                    successAction: getOverridesSuccess,
                    callback: () => {},
                }),
            );

            dispatch(END);

            await sagaTask?.toPromise();

            return {
                props: {},
            };
        },
);

export default LongDetail;
