import type { NextPage } from 'next';
import type { AppState } from '@reducers/index';
import type { HrState } from '@reducers/hr';
import type { SearchOrgasRequestPayload } from '@actions/hr/search-orgas.action';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useSelector } from 'react-redux';
import { END } from 'redux-saga';
import { MyTable } from '@components/table';
import { wrapper } from '@store/redux';
import { MyPagination } from '@components/pagination';
import { MyLayout } from '@components/Layout';
import { MyFooter } from '@components/footer';
import { useColumn } from '@hooks/use-column';
import { permissionMiddleware } from '@utils/middleware/permission';
import {
    searchOrgasSuccess,
    searchOrgasRequest,
} from '@actions/hr/search-orgas.action';
import { OrgaSearchFilterTemplate } from '@partials/hr/orga/template/SearchFilter';

const Orgas: NextPage = () => {
    const displayName = 'wr-pages-list2';

    const router = useRouter();

    const { searchOrgas } = useSelector<AppState, HrState>((props) => props.hr);

    const columns = useColumn(searchOrgas.fields);

    const handleClickRow = () => {
        alert('준비중입니다.');
        // router.replace(`/hr/user/${userid}`);
    };

    return (
        <>
            <Head>
                <title>영업조직목록</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <div className={displayName}>
                    {/* <Breadcrumb /> */}
                    <div className={`${displayName}__header`}>
                        <OrgaSearchFilterTemplate />
                    </div>
                    <div className={`${displayName}__toolbar wr-mt`}>
                        <div className={`${displayName}__total`}>
                            총합: 5,000
                        </div>
                        <div className={`${displayName}__tool`}></div>
                    </div>
                    <div className={`${displayName}__body`}>
                        <div className="wr-table--scrollable wr-table--hover">
                            <MyTable
                                columns={columns}
                                data={searchOrgas.rows}
                                pageSize={searchOrgas.lastPayload?.nums}
                                onClickRow={handleClickRow}
                            />
                        </div>
                    </div>
                    <div className={`${displayName}__footer`}>
                        <MyPagination total={100}></MyPagination>
                    </div>
                </div>
            </MyLayout>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    permissionMiddleware(async ({ dispatch, sagaTask }, ctx) => {
        const { page, nums, search, order } = ctx.query;

        const params: SearchOrgasRequestPayload = {
            page: 1,
            nums: 25,
            condition: {},
            order: {},
            successAction: searchOrgasSuccess,
        };

        if (page) {
            params.page = +(page as string);
        }
        if (nums) {
            params.nums = +(nums as string);
        }

        if (order) {
            const [type, sort] = (order as string).split(',');

            params.order[type] = sort;
        }

        if (search) {
            params.condition!['search'] = search as string;
            // if (type === 'userid') {
            //     params.condition['userid'] = String(search).toUpperCase();
            // } else if (type === 'fc') {
            //     params.condition['fc'] = search;
            // }
        }

        dispatch(searchOrgasRequest(params));

        dispatch(END);

        try {
            await sagaTask?.toPromise();
        } catch (e) {
            console.log(e);
        }

        return null;
    }),
);

export default Orgas;
