import type { NextPage } from 'next';
import type { AppState } from '@reducers/index';
import type { HrState } from '@reducers/hr';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import { END } from 'redux-saga';
import dayjs from 'dayjs';
import { MyTable } from '@components/table';
import { wrapper } from '@store/redux';
import { MyPagination } from '@components/pagination';
import { MyLayout } from '@components/Layout';
import { useColumn } from '@hooks/use-column';
import { permissionMiddleware } from '@utils/middleware/permission';
import { searchOrgasRequest } from '@actions/hr/search-orgas.action';
import { OrgaSearchFilter } from '@partials/hr/orga/template/SearchFilter';
import { getOrgasRequest } from '@actions/hr/get-orgas';
import { SearchResultTemplate } from '@partials/common/template/SearchResult';

const Orgas: NextPage = () => {
    const displayName = 'wr-pages-list2';

    const { searchOrgas } = useSelector<AppState, HrState>((props) => props.hr);

    const columns = useColumn(searchOrgas.fields);

    const handleClickRow = () => {
        alert('준비중입니다.');
        // router.replace(`/hr/user/${userid}`);
    };

    return (
        <>
            <Head>
                <title>지점명세</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <div className={displayName}>
                    <OrgaSearchFilter />
                    <SearchResultTemplate
                        total={searchOrgas.total.count}
                        pageName="조직관리 / 지점명세"
                    />
                    <div className={`${displayName}__body`}>
                        <div className="wr-table--scrollable wr-table--hover">
                            <MyTable
                                columns={columns}
                                data={searchOrgas.rows}
                                pageSize={searchOrgas.lastPayload?.nums}
                                onClickRow={handleClickRow}
                            />
                        </div>
                    </div>
                    <div className={`${displayName}__footer`}>
                        <MyPagination
                            total={searchOrgas.total.count}
                        ></MyPagination>
                    </div>
                </div>
            </MyLayout>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    permissionMiddleware(async ({ dispatch, sagaTask }, ctx, { user_info }) => {
        const { page, nums, order, date, orga, date_type, ...rest } = ctx.query;

        const params: any = {
            page: 1,
            nums: 25,
            condition: {
                idx: user_info.orga_idx,
                indate: [
                    dayjs(new Date()).format('YYYY-MM-01'),
                    dayjs(new Date()).format('YYYY-MM-DD'),
                ],
            },
            order: {},
        };
        // 페이지공통 - 페이지 번호
        if (page) {
            params.page = Number(page);
        }
        // 페이지공통 - 페이지 크기
        if (nums) {
            params.nums = Number(nums);
        }
        // 페이지공통 - 정렬
        if (order) {
            const [type, sort] = String(order).split(',');

            params.order[type] = sort;
        }
        // 영업조직
        if (orga) {
            params.idx = Number(orga);
        }
        // 입사일 및 퇴사일
        if (date_type && date) {
            params.condition[String(date_type)] = String(date).split(',');
        }
        // 조직등급, 현상태, 검색...
        for (const [key, value] of Object.entries(rest)) {
            params.condition[key] = value;
        }
        // 영업조직 목록
        dispatch(
            getOrgasRequest({
                idx: '1',
            }),
        );
        // 조직 목록
        dispatch(searchOrgasRequest(params));

        dispatch(END);

        try {
            await sagaTask?.toPromise();
        } catch (e) {
            // console.log(e);
        }

        return null;
    }),
);

export default Orgas;
