import type { NextPage } from 'next';
import type { BoardState } from '@reducers/board';
import Head from 'next/head';
import { useState } from 'react';
import { useDispatch } from 'react-redux';
import { END } from 'redux-saga';
import { MyLayout } from '@components/Layout';
import { wrapper } from '@store/redux';
import { getPostRequest } from '@actions/board/get-post.action';

const Board: NextPage<BoardState> = ({ board }) => {
    const dispatch = useDispatch();

    return (
        <>
            <Head>
                <title>게시물상세</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <div className="wr-pages-detail"></div>
            </MyLayout>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    ({ dispatch, sagaTask, getState }) =>
        async ({ req, res, query, ...etc }) => {
            const id = query.id as string;

            dispatch(getPostRequest({ id }));

            dispatch(END);

            let props = {};
            try {
                await sagaTask?.toPromise();

                props = getState().board;
            } catch (e) {
                res.statusCode = 302;

                res.setHeader('Location', '/404');
            }

            return {
                props,
            };
        },
);

export default Board;
