import type { NextPage } from 'next';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import { useState } from 'react';
import {
    getPostsRequest,
    getPostsSuccess,
} from '@actions/board/get-posts.action';
import { MyLayout } from '@components/Layout';
import { WithLabel } from '@components/WithLabel';
import { MyButton } from '@components/button';
import { MyEditor } from '@components/editor';
import { MyFooter } from '@components/footer';
import { SearchInput } from '@components/input/Search';
import { MyPagination } from '@components/pagination';
import { MySelect } from '@components/select';
import { MyTable } from '@components/table';
import { useColumn } from '@hooks/use-column';
import { useTab } from '@hooks/use-tab';
import { BoardState } from '@reducers/board';
import { AppState } from '@reducers/index';
import { IconWrapper } from '@components/IconWrapper';
import { AiOutlineFileAdd } from 'react-icons/ai';
import { AccessibleText } from '@components/AccessibleText';

const CreateBoard: NextPage = () => {
    const { boards } = useSelector<AppState, BoardState>(
        (props) => props.board,
    );

    const columns = useColumn(boards.fields);

    const tab = useTab();

    const [content, setContent] = useState<string>('');

    const handleClickRow = (row: any) => {
        tab.fire(
            `board${row.idx}`,
            `게시글(${row.title})`,
            `/board/${row.idx}`,
        );
    };

    const handleSubmit = () => {};

    return (
        <>
            <Head>
                <title>게시물등록</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <div className="wr-pages-create-board">
                    <div className="wr-pages-create-board__header">
                        <div className="row">
                            <div className="col-6">
                                <MyButton className="btn-primary">
                                    글 쓰기
                                </MyButton>
                            </div>
                        </div>
                    </div>
                    <div className="wr-pages-create-board__body wr-mt">
                        <MyEditor
                            height="500px"
                            previewStyle="tab"
                            initialEditType="wysiwyg"
                            initialValue={content}
                            onChange={(content) => setContent(content)}
                        />
                        <div className="wr-pages-create-board__attachment wr-mt">
                            <div>
                                <IconWrapper>
                                    <AiOutlineFileAdd size={20} />
                                    <AccessibleText>파일 첨부</AccessibleText>
                                </IconWrapper>
                                <span>파일 첨부</span>
                            </div>
                        </div>
                    </div>
                    <MyFooter>
                        <div className="wr-pages-detail__footer">
                            <div></div>
                            <div>
                                <MyButton
                                    type="button"
                                    className="btn-primary"
                                    onClick={handleSubmit}
                                >
                                    등록
                                </MyButton>
                            </div>
                        </div>
                    </MyFooter>
                </div>
            </MyLayout>
        </>
    );
};

export async function getServerSideProps() {
    return {
        props: {},
    };
}

export default CreateBoard;
