import type { NextPage } from 'next';
import type { LongState } from '@reducers/long';
import type { AppState } from '@reducers/index';
import type { HrState } from '@reducers/hr';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import { END } from 'redux-saga';
import { wrapper } from '@store/redux';
import { permissionMiddleware } from '@utils/middleware/permission';
import longConstants from '@constants/options/long';
import commonConstants from '@constants/options/common';
import longsService from '@services/longsService';
import { getCompaniesRequest } from '@actions/hr/get-companies';
import { findSelectOption, findSelectOptionByLabel } from '@utils/getter';
import { LongForm } from '@partials/contract/long/LongForm';
import { createUserHistory } from '@actions/common/set-user-history.action';
import { createPay } from '@actions/contract/long/set-pay.action';
import { getOrgasRequest } from '@actions/hr/get-orgas';
import { updateProduct } from '@actions/contract/common/set-product.action';
import { MyLayout } from '@components/Layout';
import { useInitCustomer, useInitTab } from '@hooks/use-initialize';
import { createInfoCust } from '@actions/contract/common/set-info-cust.action';
import { createInfoProduct } from '@actions/contract/common/set-info-product.action';
import { createBaeseo } from '@actions/contract/common/set-baeseo.action';

const Long: NextPage<LongState> = ({ long }) => {
    const { longUseCompanies } = useSelector<AppState, HrState>(
        (state) => state.hr,
    );
    // 탭 설정
    useInitTab(`장기계약상세${long.c_name ? ` - ${long.c_name}` : ''}`);
    // 계약자 설정
    useInitCustomer(long.c_idx);

    const defaultComp = findSelectOption(long.wcode, longUseCompanies);

    const defaultPayCycle = findSelectOptionByLabel(
        long.pay_cycle,
        longConstants.payCycle,
    );

    const defaultStatus = findSelectOption(long.status, longConstants.status);

    // const defaultPstatus = findSelectOption(
    //     long.pay_status,
    //     longConstants.pStatus,
    // );

    const defaultCalType = findSelectOption(
        long.cal_type,
        longConstants.calType,
    );

    const defaultSulDist = findSelectOption(
        long.sul_dist,
        commonConstants.sulDist,
    );

    const defaultSubsSubmission = findSelectOption(
        long.subs_submission,
        longConstants.subsSubmission,
    );

    let defaultFamily;
    let defaultSubsSign;
    if (long.hasOwnProperty('family')) {
        defaultFamily = findSelectOption(
            long.family ? 'Y' : 'N',
            longConstants.family,
        );
    }

    if (long.hasOwnProperty('subs_sign')) {
        defaultSubsSign = findSelectOption(
            long.subs_sign ? 'Y' : 'N',
            commonConstants.yn,
        );
    }

    return (
        <>
            <Head>
                <title>우리인슈맨라이프</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <LongForm
                    mode="update"
                    idx={long.idx}
                    defaultOrganize={long.organize}
                    defaultUserid={long.userid}
                    defaultComp={defaultComp}
                    defaultCnum={long.cnum}
                    defaultContdate={long.contdate}
                    defaultBodateto={long.bo_dateto}
                    // defaultBoDu={long.bo_du}
                    defaultPayCycle={defaultPayCycle}
                    defaultPayDateto={long.pay_dateto}
                    // defaultPayDu={long.pay_du}
                    defaultStatus={defaultStatus}
                    defaultPayStatus={long.pay_status}
                    defaultStatusDate={long.status_date}
                    defaultLastMonth={long.lastmonth}
                    defaultLastWhoi={long.lastwhoi}
                    defaultIsConfirm={long.confirm}
                    defaultPayment={long.payment.toString()}
                    defaultTp={long.tp ? long.tp.toString() : ''}
                    // defaultTp1={long.tp1 ? long.tp1.toString() : ''}
                    defaultTp2={long.tp2 ? long.tp2.toString() : ''}
                    defaultTp3={long.tp3 ? long.tp3.toString() : ''}
                    defaultTpu={long.tpu ? long.tpu.toString() : ''}
                    defaultPayBo={long.pay_bo ? long.pay_bo.toString() : ''}
                    defaultPayJ={long.pay_j ? long.pay_j.toString() : ''}
                    defaultPayS={long.pay_s ? long.pay_s.toString() : ''}
                    defaultCalType={defaultCalType}
                    defaultCalDatefrom={long.cal_datefrom}
                    defaultFamily={defaultFamily}
                    defaultSulDist={defaultSulDist}
                    defaultSubsSign={defaultSubsSign}
                    defaultSubsSubmission={defaultSubsSubmission}
                />
            </MyLayout>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    permissionMiddleware(async ({ dispatch, sagaTask }, ctx) => {
        const { query } = ctx;

        const idx = query.idx as string;

        dispatch(getOrgasRequest({}));

        dispatch(getCompaniesRequest('long-use'));

        const output: any = {
            props: {},
        };

        try {
            const { data } = await longsService.getLong({ idx });

            const long = data.data;

            output.props.long = long;

            dispatch(
                updateProduct({
                    p_code: long.p_code,
                    title: long.title,
                    spec: long.spec,
                    subcategory: long.subcategory ? long.subcategory : '',
                    cal_spec: long.cal_spec ? long.cal_spec : '',
                }),
            );

            if (long.userid_his) {
                for (let i = 0; i < long.userid_his.length; i++) {
                    dispatch(
                        createUserHistory({
                            index: i,
                            checked: false,
                            gdate: long.userid_his[i].gdate,
                            group: long.userid_his[i].group
                                ? long.userid_his[i].group
                                : '',
                            userid: long.userid_his[i].userid,
                            username: long.userid_his[i].fcname,
                        }),
                    );
                }
            }

            if (long.info_custom) {
                for (let i = 0; i < long.info_custom.length; i++) {
                    const info_custom = long.info_custom[i];

                    dispatch(
                        createInfoCust({
                            index: i,
                            checked: false,
                            key: info_custom.key,
                            value: info_custom.value,
                        }),
                    );
                }
            }

            if (long.info_product) {
                for (let i = 0; i < long.info_product.length; i++) {
                    const info_product = long.info_product[i];

                    dispatch(
                        createInfoProduct({
                            index: i,
                            checked: false,
                            key: info_product.key,
                            value: info_product.value,
                        }),
                    );
                }
            }

            // if (long.p_persons) {
            //     for (let i = 0; i < long.p_persons.length; i++) {
            //         dispatch(
            //             createInsured({
            //                 ...long.p_persons[i],
            //                 index: i,
            //                 checked: false,
            //             }),
            //         );
            //     }
            // }

            if (long.pays) {
                // 최근등록순으로 변경
                const reversedPays = long.pays.reverse();
                for (let i = 0; i < reversedPays.length; i++) {
                    const pay = reversedPays[i];

                    dispatch(
                        createPay({
                            index: i,
                            checked: false,
                            idx: pay.idx,
                            paydate: pay.paydate,
                            whoi: pay.whoi,
                            dist: pay.dist,
                            pay: pay.pay,
                            method: pay.method,
                            insert_datetime: pay.insert_datetime,
                            insert_userid: pay.insert_userid,
                            confirm: pay.confirm,
                            cals: pay.cals,
                        }),
                    );
                }
            }

            if (long.baeseos) {
                // 최근등록순으로 변경
                const reversedBaeseos = long.baeseos.reverse();
                for (let i = 0; i < long.baeseos.length; i++) {
                    const baeseo = reversedBaeseos[i];

                    dispatch(
                        createBaeseo({
                            index: i,
                            checked: false,
                            idx: baeseo.idx,
                            date: baeseo.date,
                            gdate: baeseo.gdate,
                            whoi: baeseo.whoi,
                            dist: baeseo.dist,
                            pay_point: baeseo.pay_point,
                            tp_point: baeseo.tp_point,
                            insert_datetime: baeseo.insert_datetime,
                            insert_userid: baeseo.insert_userid,
                            confirm: baeseo.confirm,
                            cals: baeseo.cals,
                        }),
                    );
                }
            }

            // if (long.contacts) {
            //     for (let i = 0; i < long.contacts.length; i++) {
            //         dispatch(
            //             createContact({
            //                 ...long.contacts[i],
            //                 index: i,
            //                 checked: false,
            //             }),
            //         );
            //     }
            // }

            dispatch(END);

            await sagaTask?.toPromise();
        } catch {
            output.redirect = {
                destination: '/404',
                permanent: true, // true로 설정하면 301 상태 코드로 리다이렉션
            };
        }

        return output;
    }),
);

export default Long;
