import type { NextPage } from 'next';
import type { AppState } from '@reducers/index';
import type { HrState } from '@reducers/hr';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import { END } from 'redux-saga';
import { wrapper } from '@store/redux';
import { permissionMiddleware } from '@utils/middleware/permission';
import { getCompaniesRequest } from '@actions/hr/get-companies';
import { getOrgasRequest } from '@actions/hr/get-orgas';
import { MyLayout } from '@components/Layout';
import { useInitTab } from '@hooks/use-initialize';
import { LongRuleForm } from '@partials/rule/long/LongRuleForm';
import { getSudistsRequest } from '@actions/rule/get-sudists';
import { getMakeableRatesRequest } from '@actions/rule/get-makeable-rates';
import { getGradesRequest } from '@actions/rule/get-grades';
import { getHwansRequest } from '@actions/rule/get-hwans';

const CreateLongRule: NextPage = () => {
    const { loggedInUser } = useSelector<AppState, HrState>(
        (state) => state.hr,
    );
    // 탭 설정
    useInitTab('장기 환수 제도');

    return (
        <>
            <Head>
                <title>우리인슈맨라이프</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <LongRuleForm
                    mode="create"
                    defaultUserid={loggedInUser.userid}
                />
            </MyLayout>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    permissionMiddleware(async ({ dispatch, sagaTask }) => {
        dispatch(getOrgasRequest({}));

        dispatch(getMakeableRatesRequest());

        dispatch(getGradesRequest());

        dispatch(getHwansRequest());

        dispatch(getSudistsRequest({ spe: 'long' }));

        dispatch(getCompaniesRequest('long-use'));

        dispatch(END);

        await sagaTask?.toPromise();

        return null;
    }),
);

export default CreateLongRule;
