import type { NextPage } from 'next';
import type { AppState } from '@reducers/index';
import type { CoreSelectOption } from '@interfaces/core';
import type { LongState } from '@reducers/long';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { END } from 'redux-saga';
import dayjs from 'dayjs';
import { DateRangePicker } from 'rsuite';
import startOfMonth from 'date-fns/startOfMonth';
import endOfMonth from 'date-fns/endOfMonth';
import addMonths from 'date-fns/addMonths';
import { MyTable } from '@components/table';
import { wrapper } from '@store/redux';
import { MySelect } from '@components/select';
import { MyPagination } from '@components/pagination';
import { WithLabel } from '@components/WithLabel';
import { SearchInput } from '@components/input/Search';
import { MyLayout } from '@components/Layout';
import { MyFooter } from '@components/footer';
import { useColumn } from '@hooks/use-column';
import { useLinkTab } from '@hooks/use-tab';
import { getOrgasRequest } from '@actions/hr/get-orgas';
import { HrState } from '@reducers/hr';
import { useSelect } from '@hooks/use-select';
import { getUsersRequest } from '@actions/hr/get-users';
import { useInput, useNumbericInput } from '@hooks/use-input';
import { MyInput } from '@components/input';
import { useDateRangepicker } from '@hooks/use-datepicker';
import { permissionMiddleware } from '@utils/middleware/permission';
import {
    GetLongsRequestPayload,
    getLongsRequest,
    getLongsSuccess,
} from '@actions/contract/long/get-longs.action';
import { DISTS } from '@constants/selectOption';
import { getCompaniesRequest } from '@actions/hr/get-companies';
import longConstants from '@constants/options/long';
import { TabModule } from '@utils/storage';

const Longs: NextPage = () => {
    const router = useRouter();

    const dispatch = useDispatch();

    const { orgas, users, longViewCompanies } = useSelector<AppState, HrState>(
        (props) => props.hr,
    );

    const { longs } = useSelector<AppState, LongState>((props) => props.long);

    const tab = useLinkTab();

    const columns = useColumn(longs.fields);

    // 검색필터 - 조직
    const [orga, setOrga] = useState<CoreSelectOption | null>(null);
    // 검색필터 - 영업가족
    const [user] = useSelect(users, null);
    // 검색필터 - 회차
    const [beforeRound] = useNumbericInput('1', { addComma: true });
    const [afterRound] = useNumbericInput('1', { addComma: true });
    // 검색필터 - 계약일자
    const [contdate, setContdate] = useDateRangepicker(null);
    // 검색필터 - 보험사
    const [company] = useSelect(longViewCompanies, null);
    // 검색필터 - 보종
    const [productType] = useSelect(longConstants.productType, null);
    // 검색필터 - 상품명
    const [ptitle] = useSelect(longs.ptitles, null);
    // 검색필터 - 납입주기
    const [cycle] = useSelect(longConstants.payCycle, null);
    // 검색필터 - 입금구분
    const [dist] = useSelect(DISTS, null);
    // 검색필터 - 검색어
    const [search] = useInput('');

    const handleChangeOrga = (org: CoreSelectOption | null) => {
        setOrga(org);

        if (org !== null) {
            dispatch(getUsersRequest({ idx: org.value }));
        }
    };

    const handleClickRow = ({ cidx, cname }: any) => {
        tab.replace(`/contract/long/${cidx}`);
    };

    const handleSearch = () => {
        let url = `/contract/long/list?page=1&nums=${longs.lastPayload!.nums}`;

        if (contdate.value !== null) {
            url += `&paydate=${contdate.value
                .map((v) => dayjs(v).format('YYYY-MM-DD'))
                .join(',')}`;
        }
        // 동일한 요청 시 reject
        if (url === router.asPath) {
            return;
        }

        const tab = new TabModule();

        tab.update('/contract/long/list', {
            to: url,
        });

        router.replace(url);
    };

    useEffect(() => {
        if (longs.lastPayload) {
            if (longs.lastPayload.condition) {
                if (longs.lastPayload.condition.paydate) {
                    setContdate(
                        longs.lastPayload.condition.paydate.map(
                            (v) => new Date(v),
                        ) as [Date, Date],
                    );
                } else {
                    setContdate(null);
                }
            }
        }
    }, [longs.lastPayload]);

    return (
        <>
            <Head>
                <title>장기계약목록</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <div className="wr-pages-long-list">
                    {/* <Breadcrumb /> */}
                    <div className="wr-pages-long-list__header">
                        <div className="row">
                            <div className="col">
                                <div className="row">
                                    <div className="col">
                                        <WithLabel
                                            id="orga"
                                            label="조직"
                                            type="active"
                                        >
                                            <MySelect
                                                inputId="orga"
                                                options={orgas}
                                                value={orga}
                                                onChange={handleChangeOrga}
                                            />
                                        </WithLabel>
                                    </div>
                                    <div className="col">
                                        <WithLabel
                                            id="fc"
                                            label="영업가족"
                                            type="active"
                                        >
                                            <MySelect inputId="fc" {...user} />
                                        </WithLabel>
                                    </div>
                                </div>

                                <div className="row wr-mt">
                                    <div className="col">
                                        <div className="row">
                                            <div className="col">
                                                <WithLabel
                                                    id="company"
                                                    label="보험사"
                                                    type="active"
                                                >
                                                    <MySelect
                                                        inputId="company"
                                                        {...company}
                                                    />
                                                </WithLabel>
                                            </div>
                                            <div className="col">
                                                <WithLabel
                                                    id="product_type"
                                                    label="보종"
                                                    type="active"
                                                >
                                                    <MySelect
                                                        inputId="product_type"
                                                        {...productType}
                                                    />
                                                </WithLabel>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="col">
                                        <WithLabel
                                            id="ptitle"
                                            label="상품명"
                                            type="active"
                                        >
                                            <MySelect
                                                inputId="ptitle"
                                                {...ptitle}
                                            />
                                        </WithLabel>
                                    </div>
                                </div>
                            </div>
                            <div className="col">
                                <div className="row">
                                    <div className="col">
                                        <WithLabel
                                            id="round"
                                            label="회차"
                                            type="active"
                                        >
                                            <MyInput
                                                type="text"
                                                id="round"
                                                className="text-end"
                                                placeholder="입력"
                                                {...beforeRound}
                                            />
                                            <div
                                                className="wr-with__extension wr-form__unit wr-border-l--hide"
                                                style={{ height: 30 }}
                                            >
                                                ~
                                            </div>
                                            <MyInput
                                                type="text"
                                                id="round_after"
                                                className="text-end wr-border-l--hide"
                                                placeholder="입력"
                                                {...afterRound}
                                            />
                                        </WithLabel>
                                    </div>
                                    <div className="col">
                                        <WithLabel
                                            id="datepicker"
                                            label="계약일자"
                                            type="active"
                                        >
                                            <DateRangePicker
                                                id="datepicker"
                                                format="yyyy-MM-dd"
                                                placeholder="기간을 입력 혹은 선택하세요"
                                                size="sm"
                                                placement="autoVerticalEnd"
                                                {...contdate}
                                                style={{
                                                    width: '100%',
                                                }}
                                                ranges={[
                                                    {
                                                        label: '전월',
                                                        value: [
                                                            startOfMonth(
                                                                addMonths(
                                                                    new Date(),
                                                                    -1,
                                                                ),
                                                            ),
                                                            endOfMonth(
                                                                addMonths(
                                                                    new Date(),
                                                                    -1,
                                                                ),
                                                            ),
                                                        ],
                                                    },
                                                    {
                                                        label: '당월',
                                                        value: [
                                                            startOfMonth(
                                                                new Date(),
                                                            ),
                                                            new Date(),
                                                        ],
                                                    },
                                                ]}
                                            />
                                        </WithLabel>
                                    </div>
                                </div>
                                <div className="row wr-mt">
                                    <div className="col">
                                        <WithLabel
                                            id="cycle"
                                            label="납입주기"
                                            type="active"
                                        >
                                            <MySelect
                                                inputId="cycle"
                                                {...cycle}
                                            />
                                        </WithLabel>
                                    </div>
                                    <div className="col">
                                        <div className="row">
                                            <div className="col">
                                                <WithLabel
                                                    id="dist"
                                                    label="입금구분"
                                                    type="active"
                                                >
                                                    <MySelect
                                                        inputId="dist"
                                                        {...dist}
                                                    />
                                                </WithLabel>
                                            </div>

                                            <div className="col">
                                                <WithLabel
                                                    id="search"
                                                    label="검색"
                                                    type="active"
                                                >
                                                    <SearchInput
                                                        id="search"
                                                        placeholder="검색어를 입력하세요"
                                                        {...search}
                                                        onSearch={handleSearch}
                                                    />
                                                </WithLabel>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="wr-pages-long-list__body wr-mt">
                        <div className="wr-table--scrollable wr-table--hover">
                            <MyTable
                                columns={columns}
                                data={longs.rows}
                                pageSize={longs.lastPayload?.nums}
                                onClickRow={handleClickRow}
                            />
                        </div>
                    </div>
                    <MyFooter>
                        <MyPagination
                            // requestAction={getLongsRequest}
                            // successAction={getLongsSuccess}
                            payload={longs.lastPayload}
                            total={longs.total.count}
                        >
                            <span>
                                건수: {longs.total.count.toLocaleString()}
                            </span>
                            <span>
                                실적보험료계: {longs.total.pay.toLocaleString()}
                            </span>
                            <span>
                                수정보험료계:
                                {longs.total.tp
                                    ? longs.total.tp.toLocaleString()
                                    : 0}
                            </span>
                        </MyPagination>
                    </MyFooter>
                </div>
            </MyLayout>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    permissionMiddleware(async ({ dispatch, sagaTask }, ctx) => {
        const { page, nums, paydate } = ctx.query;

        const params: GetLongsRequestPayload = {
            page: 1,
            nums: 25,
            condition: {
                paydate: [
                    dayjs(new Date()).format('YYYY-MM-01'),
                    dayjs(new Date()).format('YYYY-MM-DD'),
                ],
            },
            successAction: getLongsSuccess,
        };

        if (page) {
            params.page = +(page as string);
        }
        if (nums) {
            params.nums = +(nums as string);
        }
        if (paydate) {
            params.condition!['paydate'] = (paydate as string).split(',');
        }

        dispatch(getLongsRequest(params));

        dispatch(getCompaniesRequest('long-view'));

        dispatch(
            getOrgasRequest({
                idx: '1',
            }),
        );

        dispatch(getUsersRequest({ idx: '1' }));

        dispatch(END);

        try {
            await sagaTask?.toPromise();
        } catch (e) {
            console.log(e);
        }

        return null;
    }),
);

export default Longs;
