import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { useDispatch } from 'react-redux';
import { MyEditor } from '@components/editor';

// const CreatePost: NextPage = () => {
//     const dispatch = useDispatch();

//     const [content, setContent] = useState<string>('');

//     const handleChangeContent = (content: string) => {
//         setContent(content);
//     };

//     return (
//         <>
//             <Head>
//                 <title>포스트 생성페이지</title>
//                 <meta
//                     name="description"
//                     content="Generated by create next app"
//                 />
//             </Head>
//             <div className="wr-pages-create-post">
//                 {/* <Breadcrumb /> */}
//                 <div>
//                     <h2>제목</h2>
//                 </div>
//                 <div>
//                     <MyEditor
//                         initialValue={content}
//                         valueType="html"
//                         initialEditType="wysiwyg"
//                         onChange={handleChangeContent}
//                     />
//                 </div>
//             </div>
//         </>
//     );
// };

// export default CreatePost;

const Main: NextPage = () => {
    return (
        <>
            <Head>
                <title>redirect</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
        </>
    );
};

export async function getServerSideProps() {
    const redirectUrl = '/login';

    return {
        redirect: {
            destination: redirectUrl,
            permanent: false, // true로 설정하면 301 상태 코드로 리다이렉션
        },
    };
}

export default Main;
