import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { useDispatch } from 'react-redux';
import { MyEditor } from '@components/editor';

const CreatePost: NextPage = () => {
    const dispatch = useDispatch();

    const [content, setContent] = useState<string>('');

    const handleChangeContent = (content: string) => {
        setContent(content);
    };

    return (
        <>
            <Head>
                <title>포스트 생성페이지</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wr-pages-create-post">
                {/* <Breadcrumb /> */}
                <div>
                    <h2>제목</h2>
                </div>
                <div>
                    <MyEditor
                        initialValue={content}
                        valueType="html"
                        initialEditType="wysiwyg"
                        onChange={handleChangeContent}
                    />
                </div>
            </div>
        </>
    );
};

export default CreatePost;
