import type { NextPage } from 'next';
import Head from 'next/head';

const Main: NextPage = () => {
    return (
        <>
            <Head>
                <title>redirect</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
        </>
    );
};

export async function getServerSideProps() {
    const redirectUrl = '/login';

    return {
        redirect: {
            destination: redirectUrl,
            permanent: false, // true로 설정하면 301 상태 코드로 리다이렉션
        },
    };
}

export default Main;
