import type { NextPage } from 'next';
import type { FormEvent, MouseEvent } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { FaUser, FaKey, FaPowerOff, FaHeadset } from 'react-icons/fa';
import { setCookie, deleteCookie, getCookie } from 'cookies-next';
import { MyCheckbox } from '@components/checkbox';
import { useInput } from '@hooks/use-input';
import { wrapper } from '@store/redux';
import externalsService from '@services/externalsService';
import hrsService from '@services/hrsService';
import { commonAxiosErrorHandler } from '@utils/error';
import { useCheckbox } from '@hooks/use-checkbox';
import { isEmpty } from '@utils/validator/common';

interface LoginPageProps {
    ip: string;
}

const Login: NextPage<LoginPageProps> = ({ ip }) => {
    const displayName = 'wr-pages-login';

    const router = useRouter();

    const [userid, setUserid] = useInput('');

    const [password] = useInput('');

    const [checkSaveId, setCheckSaveId] = useCheckbox(false);

    const handleResetPassword = (evt: MouseEvent<HTMLAnchorElement>) => {
        evt.preventDefault();

        alert('준비중입니다.');
    };

    const handleSubmit = async (evt: FormEvent) => {
        evt.preventDefault();

        try {
            const { data } = await hrsService.login({
                ip,
                userid: userid.value,
                password: password.value,
            });

            const { access_token } = data;

            if (access_token) {
                const tokenKey = process.env.COOKIE_TOKEN_KEY;
                if (isEmpty(tokenKey)) {
                    return alert('인증키 발급 중 오류가 발생했습니다.');
                } else {
                    setCookie(tokenKey!, access_token, {
                        maxAge: 60 * 60 * 24,
                    });
                }

                const idKey = process.env.COOKIE_RECENT_LOGIN_KEY;
                if (isEmpty(idKey)) {
                    alert('error: COOKIE_RECENT_LOGIN_KEY is empty');
                } else {
                    if (checkSaveId.checked) {
                        setCookie(idKey!, userid.value, {
                            maxAge: 60 * 60 * 24 * 365,
                        });
                    } else {
                        deleteCookie(idKey!);
                    }
                }

                router.replace('/contract/long/bo');
            }
        } catch (e) {
            const { message } = commonAxiosErrorHandler(e);

            alert(message);
        }
    };

    useEffect(() => {
        const idKey = process.env.COOKIE_RECENT_LOGIN_KEY || '';

        const _userid = getCookie(idKey) as string;
        if (_userid) {
            setUserid(_userid);

            setCheckSaveId(true);
        }
    }, []);

    return (
        <>
            <Head>
                <title>우리인슈맨라이프</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <div className={`${displayName}__wrap`}>
                <div className={`${displayName}`}>
                    <div className={`${displayName}__left`}>
                        <img
                            src="/static/images/main.png"
                            alt="Wooriinsumanlife"
                        />
                    </div>
                    <div className={`${displayName}__right`}>
                        <div className={`${displayName}__header`}>
                            <div className={`${displayName}__secret`}>
                                대외비
                            </div>
                        </div>
                        <form
                            className={`${displayName}__body`}
                            onSubmit={handleSubmit}
                        >
                            <div className="wr-login-input__wrap">
                                <div className="wr-login-input__icon">
                                    <FaUser size={30} />
                                </div>
                                <input
                                    id="userid"
                                    className="wr-login-input"
                                    placeholder="사원번호"
                                    required
                                    {...userid}
                                />
                            </div>
                            <div className="wr-login-input__wrap">
                                <div className="wr-login-input__icon">
                                    <FaKey size={30} />
                                </div>
                                <input
                                    type="password"
                                    id="password"
                                    className="wr-login-input"
                                    placeholder="Password"
                                    required
                                    {...password}
                                />
                            </div>
                            <button
                                type="submit"
                                className={`${displayName}__button wr-mt`}
                            >
                                <span className="wr-btn btn">로그인</span>
                                <div>
                                    <FaPowerOff size={25} />
                                </div>
                            </button>
                        </form>
                        <div className={`${displayName}__services`}>
                            <div>
                                <MyCheckbox
                                    id="save_id"
                                    label="사원번호 또는 ID 저장"
                                    {...checkSaveId}
                                />
                            </div>
                            <div className={`${displayName}__expand`}>
                                <a
                                    onClick={handleResetPassword}
                                    className={`${displayName}__reset`}
                                >
                                    비밀번호 초기화
                                </a>
                            </div>
                        </div>
                        <div className={`${displayName}__phone`}>
                            <div>
                                <FaHeadset size={25} />
                            </div>
                            <div>Help Desk 070-4881-6003</div>
                        </div>
                        <div className={`${displayName}__services wr-mt`}>
                            <a
                                className="btn btn-success w-100 text-center"
                                href="https://939.co.kr/7800"
                                target="_blank"
                                rel="noreferrer"
                            >
                                본사원격지원
                            </a>
                        </div>
                        <div className={`${displayName}__footer`}>
                            <span>
                                우리인슈맨라이프 사용자를 위한 시스템으로
                                인가된분만 사용가능합니다.
                            </span>
                            <br />
                            <span>
                                Copyrightⓒ by Wooriinsumanlife Co., Ltd. All
                                rights reserved
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    (_) => async (_) => {
        let ip = '';

        try {
            const { data } = await externalsService.getIp({ isIPv6: true });

            ip = data.ip;
        } catch {
            console.error(
                '[ERROR|LOGIN:getIp] - 해당 사용자는 IPv6환경이 아님',
            );
        }

        return {
            props: {
                ip,
            },
        };
    },
);

export default Login;
