import type { NextPage } from 'next';
import Head from 'next/head';
import { MyLayout } from '@components/Layout';

const Test: NextPage = () => {
    return (
        <>
            <Head>
                <title>우리인슈맨라이프 - 404</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <div className="row">
                    <div className="col">
                        <iframe
                            src="https://wportal.co.kr/app-web/03_car/estimate.asp"
                            width="100%"
                            height="100%"
                        />
                    </div>
                </div>
            </MyLayout>
        </>
    );
};

export default Test;
