import type { NextPage } from 'next';
import Head from 'next/head';
import { MyLayout } from '@components/Layout';

const Test: NextPage = () => {
    return (
        <>
            <Head>
                <title>우리인슈맨라이프 - 404</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <h2>내용을 입력하세요</h2>
            </MyLayout>
        </>
    );
};

export default Test;
