import type { NextPage } from 'next';
import Head from 'next/head';
import { END } from 'redux-saga';
import { MyLayout } from '@components/Layout';
import { wrapper } from '@store/redux';
import { permissionMiddleware } from '@utils/middleware/permission';
import { getOrgasRequest } from '@actions/hr/get-orgas';
import { getCompaniesRequest } from '@actions/hr/get-companies';
import { CarCompareForm } from '@partials/contract/car/CompareForm';

const ComparisonCar: NextPage = () => {
    return (
        <>
            <Head>
                <title>비교견적(자동차)</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MyLayout>
                <CarCompareForm />
            </MyLayout>
        </>
    );
};

export const getServerSideProps = wrapper.getServerSideProps(
    permissionMiddleware(async ({ dispatch, sagaTask }) => {
        dispatch(getOrgasRequest({}));

        dispatch(getCompaniesRequest('car-use'));

        dispatch(END);

        await sagaTask?.toPromise();

        return null;
    }),
);

export default ComparisonCar;
